### PR TITLE
Mod/PartDesign: add champfer or fillet old workflow support

### PR DESCRIPTION
**Pull request by Fat-Zer**
Also rework finishFeature() so at least champfer and fillet may be
inserted into any place(not only to the tip) of any apropriate body(not only the active one) of the body.

### CODE REVIEW

**Comment by DeepSOIC** [comment]
Hi!
commit fa06e603251bf004358f7bdfca1bd1cc8c74df1b includes some changes to PartDesign Loft, but it isn't mentioned in commit message. Can you please fix it (I suggest splitting it off into a separate commit, although the changes will probably be squashed later...)

**Comment by Fat-Zer** [comment]
where exactly? I don't see anything regard loft. there...

**Comment by DeepSOIC** [comment]
Ah, stupid me. I didn't read the code carefully enough =)
stupid-me-loft

**Comment by DeepSOIC** [comment]
It works, we are getting close =)

**Pull request merged**
